# Generated by Django 3.1.1 on 2020-09-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='fcmSettings',
            field=models.JSONField(default=dict),
        ),
    ]
