# Generated by Django 3.1.1 on 2020-09-15 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0002_auto_20200915_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='accessToken',
            field=models.TextField(blank=True, default=uuid.uuid4),
        ),
    ]
